version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker
    environment:
      JFROG_IMAGE: tictrac.jfrog.io/tictrac/infra-tools

jobs:
  build:
    executor:
      name: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: apk add bash curl
      - run:
          name: Build Docker image
          command: docker build -t $JFROG_IMAGE:$CIRCLE_SHA1 .
      - run:
          name: Prepare and Upload Docker images
          command: |
            if [[ "$CIRCLE_TAG" != "" ]]; then
              echo "Preparing Docker tags and uploading Docker images"
              docker login -u $JFROG_USERNAME -p $JFROG_PASSWORD tictrac.jfrog.io
              docker tag $JFROG_IMAGE:$CIRCLE_SHA1 $JFROG_IMAGE:$CIRCLE_TAG
              docker push $JFROG_IMAGE:$CIRCLE_TAG
            else
              echo "Docker images uploading enabled only for Git Tag event"
            fi
      - slack/status

workflows:
  tictrac:
    jobs:
      - build:
          name: Docker build
          context: Infrastructure
          filters:
            tags:
              only: /^.*/
            branches:
              only: /.*/

orbs:
  slack: circleci/slack@3.4.2
